const usersDB = {
  users: require("../model/users.json"),
  setUsers: function (data) {
    this.users = data;
  },
};

const jwt = require("jsonwebtoken");
require("dotenv").config();

//a controller that handles access token refreshing

const handleRefreshToken = (req, res) => {
  const cookies = req.cookies;
  //check if cookies exist in user's browser
  //then check if there's a jwt token stored in the cookie
  // console.log(cookies.jwt);
  if (!cookies?.jwt) return res.sendStatus(401); //unauthorized

  const refreshToken = cookies.jwt;
  // console.log(refreshToken);

  //check which user holds that jwt in the database
  //to determine who is making the request
  const existUser = usersDB.users.find(
    (user) => user.refreshToken === refreshToken
  );
  if (!existUser) return res.sendStatus(403); //forbidden

  //check if the refresh token was a valid token
  //generated by the server
  jwt.verify(refreshToken, process.env.REFRESH_TOKEN_SECRET, (err, decoded) => {
    //return status 403 if jwt is invalid (jwt is not created by the server) or
    //the username in the database that was matched with the jwt token
    //does not match with the decoded username frow the jwt token (jwt token was tampered)
    if (err || existUser.username !== decoded.username)
      return res.sendStatus(403); //forbidden

    //create a new access token
    const accessToken = jwt.sign(
      { username: decoded.username },
      process.env.ACCESS_TOKEN_SECRET,
      { expiresIn: "30s" }
    );
    console.log(accessToken);
    res.json({ accessToken });
  });
  // next();
};

module.exports = { handleRefreshToken };
